---
- name: Create a special file
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    file_content: "Success! You done did an Ansible!"
    file_path: "/tmp/challenge_dir/"
    file_name: "challenge_file.txt"

  roles:
    - arista_backup2
  tasks:
    -name: Print a mesage
    debug:
      msg: "The roles section will run before any tasks."
